-- Immutable once applied. Future schema changes require a new migration.
CREATE TABLE public.catalog_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(16) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT catalog_item_sku_not_blank CHECK (btrim(sku) <> ''),
    CONSTRAINT catalog_item_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT catalog_item_description_not_blank CHECK (btrim(description) <> ''),
    CONSTRAINT catalog_item_type_valid CHECK (type IN ('PRODUCT', 'SERVICE')),
    CONSTRAINT catalog_item_price_nonnegative CHECK (price >= 0),
    CONSTRAINT catalog_item_timestamps_ordered CHECK (updated_at >= created_at)
);
